### ISSUE TITLE
Cube and Teapot

### ISSUE THREAD

**Issue by brandonforster** [ahoran3/Project3#7]
Cube and teapot are currently very broken. All of the elements of the teapot (the regular, reflection and shadow) are drawn at the exact same place and it looks really bad. The cube is either not drawn at all or it isn't being correctly scaled.

Neither of these are huge issues since neither model can be in the final product, but it indicates problems with the code.

**Comment by ahoran3** [comment]
Sorry, didn't see this till just now. Yeah, I've been working on them for a while. Got a new version up a bit ago that has most of those issues fixed. The cube was rendering, it was just super tiny. I beefed if up a bit.

Im going to fix shadows and reflection for all instances of each rendered model now, because currenly it is only putting them on the first of each one.

At least we're making steady progress.

After that I've really got to start my PA10.
